### ISSUE TITLE
Carto SQL API fails to reply within 60 seconds

### ISSUE THREAD

**Issue by tymur-mamedov-epam** [CartoDB/mobile-ios-samples#7] opened 2016-10-26 18:40 UTC
Quite often [Carto SQL API](https://carto.com/docs/carto-engine/sql-api/making-calls/#json) fails to reply within 60 seconds. While other requests take a few seconds or less.

**Comment by mtehver** [comment] 2016-11-01 10:22
Could this be related to the query you are using? 60 seconds usually means either a very complex query or huge number of query results.

**Comment by tymur-mamedov-epam** [comment] 2016-11-02 19:05
It seems to be failing for zoom level 1 or 2. It does not seem to be failing for zoom level 3, even though the structure of the query and the number of results for this zoom level is the same.

**Comment by mtehver** [comment] 2016-11-03 14:29
Any chance you could share your code? If you try to use SQL API directly (via browser, for example), do you get results without delay?

**Comment by Nikituh** [comment] 2017-02-06 08:39
Closing, as it no longer relevant: we cannot reproduce and @tymur-mamedov-epam is MIA.

**Closed as completed by Nikituh** 2017-02-06 08:39 UTC
